# .github/workflows/build.yml
name: Build Linux & Windows

on:
  push:
    tags:
      - 'v*'  # Only build on version tags
  workflow_dispatch:  # Manual trigger for testing

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.0'
          modules: 'qtmultimedia'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ffmpeg libavcodec-dev libavformat-dev libavutil-dev libswresample-dev \
            libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            libpulse-dev libasound2-dev libxcb-cursor0
      
      - name: Build
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
          make -j$(nproc)
      
      - name: Create AppImage
        run: |
          wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x *.AppImage
          
          DESTDIR=AppDir make install -C build
          ./linuxdeploy-x86_64.AppImage --appdir AppDir --plugin qt --output appimage
          
          mv *.AppImage FFAB-${{ github.ref_name }}-linux-x86_64.AppImage
      
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: '*.AppImage'

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.0'
          modules: 'qtmultimedia'
          arch: 'win64_msvc2019_64'
      
      - name: Install FFmpeg
        run: |
          choco install ffmpeg-full -y
          # Or download specific build:
          # curl -L -o ffmpeg.zip https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip
      
      - name: Build
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
      
      - name: Package
        run: |
          mkdir package
          cp build/Release/FFAB.exe package/
          windeployqt package/FFAB.exe --release --no-translations
          # Copy FFmpeg DLLs too
      
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: package/

  release:
    needs: [linux, windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            linux-build/*.AppImage
            windows-build/*
          draft: true  # Review before publishing